### PR TITLE
feat(client): add generator config to generate Ledger java client

### PR DESCRIPTION
**Pull request by edwardmp**
# Add generator config to generate Ledger java client

I’ve tried to mimic what you did for the SDKs for other languages. There’s a few open things though which are probably best for Formance to pick up.

- [ ] Formance needs to define release process  (.github/workflows/release.yml.mustache) + create repo
- [ ] Formance needs to define licenseName/licenseUrl (in [additionalProperties](https://github.com/numary/ledger/blob/502856bfc4f3725416870c72cfd72389979e9a2e/sdk/configs/java.yaml#L5))
- [ ] Please define servers url in swagger.json so that when generating not the hardcoded “localhost” is used. This needs to be fixed before the SDK can
really be used by others. Please see https://stackoverflow.com/a/72182063/1422070 for a good approach I believe
- [ ] For some reason, a few classes are named like `GetAccount200Response` by  default. I use inlineSchemaNameMappings setting to manually override this to a
normal name (like `GetAccountResponse`). There are also classes for error status codes like `GetAccount400Response`, but although these are generated they are not used by other classes, so I don’t bother with renaming those at this time. But perhaps we can skip generation somehow?
- [ ] Tests are generated but they don’t actually do anything. I can define some manual tests, just not sure what your strategy is here. Just define them
manually and include them in the final repo? It seems that’s what you do for the Python SDK

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Refactoring / Technical debt

## What parts of the code are impacted ?
No direct impact, since the github workflows still need to be modified to call the generation task for Java.

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by edwardmp** [comment]
Some usage examples:

```java
    @Bean
    fun ledgerClient(): ApiClient {
        val apiClient = ApiClient("basicAuth", "", "")

        apiClient.adapterBuilder.baseUrl("http://localhost:3068")

        return apiClient
    }
    
    fun executeNumScript(ledgerName: String, plainScriptContents: String, scriptVars: Map<String, Object>? = null) : ScriptResult? {
        val readText = javaClass.classLoader.getResource("ledger/test.numscript").readText(Charsets.UTF_8)

        val script = Script()
        script.plain = readText
        script.vars = scriptVars

        return apiClient.createService(ScriptApi::class.java).runScript(ledgerName, script, false).execute().body()
    }
```

**Comment by gfyrag** [comment]
Hi @edwardmp !
I merged your PR inside #288 to do some modification.

Concerning your remarks, we will create a guidelines to how to add a new sdk.

After internal discussion, we decided that MIT should be a correct licence for this kind of code.

Concerning tests, we don't have a clear process about how to integrate them.
For python, php, node, and go, those have been added after the repository generation. 
Doing like that involves a two step process which i don't like.

We recently add the "servers" missing property on the openapi spec (see #278).

Concerning your point about generated class names, we will work on the swagger to make the generated code more cleaner.

**Comment by edwardmp** [comment]
@gfyrag sounds good! Thanks

**Comment by flemzord** [comment]
@all-contributor please add @edwardmp for code

**Comment by flemzord** [comment]
@all-contributors please add @edwardmp for code

**Comment by edwardmp** [comment]
Hi @flemzord, any plans on when the Java client library will be published to Maven central or any other package repository?

**Comment by flemzord** [comment]
Hey @edwardmp, this repository is now public :)

**Comment by edwardmp** [comment]
Hi @flemzord , is it correct that I still can not find it on Maven central or any other repository?

**Pull request closed without merging**
