### PR TITLE
chore: remove duplicate go mod vendor

### PR DESCRIPTION
**Pull request by edwardmp**
# Title

Test already depends on vendor task, which already runs `go mod vendor`

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Refactoring / Technical debt

## What parts of the code are impacted ?
Taskfile for Go SDK

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by flemzord** [comment]
Thanks @edwardmp for your PR ! 
It's possible to follow [this rules ](https://github.com/numary/ledger/blob/main/CONTRIBUTING.md) ?

**Review by gfyrag — APPROVED** [review]

**Review by antoinegelloz — APPROVED** [review]
Thank you Edward for your contribution :)

**Comment by edwardmp** [comment]
Thanks will change PR soon

**Comment by edwardmp** [comment]
@flemzord updated the commit message!

**Review by gfyrag — APPROVED** [review]

**Review by flemzord — APPROVED** [review]

**Pull request merged**
